#!/bin/bash

shopt -s lastpipe
tmux list-panes | wc -l | read number
if [ $number -lt 2 ]; then
	tmux splitw -$1 -p $2 -c "#{pane_current_path}"
	if [ -n "$3" ]; then
		tmux send -t 2 source\ $3 Enter
	fi
	if [[ "$1" == "v" ]]; then
		tmux select-pane -U
	else
		tmux select-pane -L
	fi
fi

