#!/bin/bash

shopt -s lastpipe
tmux list-panes | wc -l | read number
if [ $number -lt 2 ]; then
	if [[ "$1" == "v" ]]; then
		tmux splitw -v -p 23 -c "#{pane_current_path}"
		tmux select-pane -U
	fi
	if [[ "$1" == "h" ]]; then
		tmux splitw -h -p 38 -c "#{pane_current_path}"
		tmux select-pane -L
	fi
fi

