#!/bin/bash

shopt -s lastpipe
tmux list-panes | wc -l | read number
if [ $number -lt 2 ]; then
	tmux splitw -h -p 38 -c "#{pane_current_path}"
	tmux select-pane -L
fi
if [[ "$@" == *.py ]]; then 
	# tmux send -t 2 'copython '$@' 2>&1 | tee -a '$@'.log' Enter
	tmux send -t 2 'copython '$@'' Enter

elif [[ "$@" == *.js ]]; then 
	# tmux send -t 2 'copython '$@' 2>&1 | tee -a '$@'.log' Enter
	tmux send -t 2 'node '$@'' Enter

else
	# tmux send -t 2 './'$@' 2>&1 | tee -a '$@'.log' Enter
	tmux send -t 2 './'$@'' Enter
fi
